### ISSUE TITLE
Is this intentionally public?

### ISSUE THREAD

**Issue by abremges** [hzi-bifo/AntiPatch#1]
If yes: Great, I love it!
Else: https://github.com/hzi-bifo/AntiPatch/settings 'Make this repository private'

**Comment by TRKlingen** [comment]
Yes, I use it to provide code for a publication.

---

Thorsten Klingen
PhD Student

Computational Biology of Infection Research
Helmholtz Centre for Infection Research
Inhoffenstraße 7x-apple-data-detectors://0
38124 Braunschweigx-apple-data-detectors://0
Germanyx-apple-data-detectors://0

http://www.helmholtz-hzi.de/en/research/research_topics/bacterial_and_viral_pathogens/computational_biology_of_infection_research/

On 15.04.2015, at 12:58, Andreas Bremges <notifications@github.com<mailto:notifications@github.com>> wrote:

If yes: Great, I love it!
Else: https://github.com/hzi-bifo/AntiPatch/settings 'Make this repository private'

—
Reply to this email directly or view it on GitHubhttps://github.com/hzi-bifo/AntiPatch/issues/1.

---

Helmholtz-Zentrum für Infektionsforschung GmbH | Inhoffenstraße 7 | 38124 Braunschweig | www.helmholtz-hzi.de
Das HZI ist seit 2007 zertifiziertes Mitglied im "audit berufundfamilie"
50 Jahre Spitzenforschung - 50 Jahre HZI: www.helmholtz-hzi.de/50

Vorsitzende des Aufsichtsrates: MinDir’in Bärbel Brumme-Bothe, Bundesministerium für Bildung und Forschung
Stellvertreter: MinDirig Rüdiger Eichel, Niedersächsisches Ministerium für Wissenschaft und Kultur
Geschäftsführung: Prof. Dr. Dirk Heinz; Franziska Broer
Gesellschaft mit beschränkter Haftung (GmbH)
Sitz der Gesellschaft: Braunschweig
Handelsregister: Amtsgericht Braunschweig, HRB 477

**Comment by abremges** [comment]
Okay, thanks. Closing this issue then.
(You can toggle private/public at any point.)
